# itk-version: 1.0.0

version: "3"

services:
  phpfpm:
    image: itkdev/php8.1-fpm:latest
    environment:
      - XDEBUG_MODE=${XDEBUG_MODE:-off}
      - XDEBUG_SESSION=${XDEBUG_SESSION:-0}
      - COMPOSER_VERSION=2
      - DOCKER_HOST_DOMAIN=${COMPOSE_DOMAIN}
      - PHP_IDE_CONFIG=serverName=localhost
    volumes:
      - .:/app:delegated
