# config/services.yaml
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name

  ItkDev\OpenIdConnectBundle\:
    resource: '../../../src/*'
    exclude:
      - '../../../src/DependencyInjection/'
      - '../../../src/Kernel.php'
      - '../../../src/Tests/'


  ItkDev\OpenIdConnect\Security\OpenIdConfigurationProvider:
    arguments:
      $options: ~
      $collaborators: ~

  #ItkDev\OpenIdConnectBundle\Controller\LoginController:
  #  arguments:
  #    $provider: ~

  ItkDev\OpenIdConnectBundle\Security\OpenIdLoginAuthenticator:
    arguments:
      $provider: ~
      $session: ~