# config/services.yaml
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  ItkDev\OpenIdConnect\Security\OpenIdConfigurationProvider:
    public: true
    arguments:
      $options: ~
      $collaborators: ~

  ItkDev\OpenIdConnectBundle\Controller\LoginController:
    public: true
    arguments:
      $provider: '@ItkDev\OpenIdConnect\Security\OpenIdConfigurationProvider'

  ItkDev\OpenIdConnectBundle\Security\OpenIdLoginAuthenticator:
    public: true
    arguments:
      $provider: '@ItkDev\OpenIdConnect\Security\OpenIdConfigurationProvider'
      $session: ~

  ItkDev\OpenIdConnectBundle\Util\CliLoginHelper:
    public: true
    arguments:
      $cache: ~

  ItkDev\OpenIdConnectBundle\Command\UserLoginCommand:
    public: true
    arguments:
      $cliLoginHelper: '@ItkDev\OpenIdConnectBundle\Util\CliLoginHelper'
      $cliLoginRedirectRoute: ~
      $urlGenerator: '@Symfony\Component\Routing\Generator\UrlGeneratorInterface'
      $userProvider: '@Symfony\Component\Security\Core\User\UserProviderInterface'

  ItkDev\OpenIdConnectBundle\Security\LoginTokenAuthenticator:
    public: true
    arguments:
      $cliLoginHelper: '@ItkDev\OpenIdConnectBundle\Util\CliLoginHelper'
      $cliLoginRedirectRoute: ~

  Symfony\Component\Routing\Generator\UrlGeneratorInterface:
    public: true

  Symfony\Component\Security\Core\User\UserProviderInterface:
    public: true