# config/services.yaml
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  ItkDev\OpenIdConnect\Security\OpenIdConfigurationProvider:
    arguments:
      $options: ~
      $collaborators: ~

  ItkDev\OpenIdConnectBundle\Controller\LoginController:
    arguments:
      $provider: '@ItkDev\OpenIdConnect\Security\OpenIdConfigurationProvider'

  ItkDev\OpenIdConnectBundle\Security\OpenIdLoginAuthenticator:
    arguments:
      $provider: ~
      $session: ~