# config/services.yaml
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  ItkDev\OpenIdConnectBundle\Controller\LoginController:
    public: true
    arguments:
      $providers: !tagged_iterator { tag: 'open_id_connect.login_provider', index_by: 'key' }

  ItkDev\OpenIdConnectBundle\Security\OpenIdLoginAuthenticator:
    public: true
    arguments:
      $providers: !tagged_iterator { tag: 'open_id_connect.login_provider', index_by: 'key' }
      $session: ~

  ItkDev\OpenIdConnectBundle\Util\CliLoginHelper:
    public: true
    arguments:
      $cache: ~

  ItkDev\OpenIdConnectBundle\Command\UserLoginCommand:
    public: true
    arguments:
      $cliLoginHelper: '@ItkDev\OpenIdConnectBundle\Util\CliLoginHelper'
      $cliLoginRedirectRoute: ~

  ItkDev\OpenIdConnectBundle\Security\LoginTokenAuthenticator:
    public: true
    arguments:
      $cliLoginHelper: '@ItkDev\OpenIdConnectBundle\Util\CliLoginHelper'
      $cliLoginRedirectRoute: ~
