# config/services.yaml
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  ItkDev\OpenIdConnectBundle\Security\OpenIdConfigurationProviderManager:
      public: true
      arguments:
          $config: ~

  ItkDev\OpenIdConnectBundle\Controller\LoginController:
    public: true

  ItkDev\OpenIdConnectBundle\Security\OpenIdLoginAuthenticator:
    public: true

  ItkDev\OpenIdConnectBundle\Util\CliLoginHelper:
    public: true
    arguments:
      $cache: ~

  ItkDev\OpenIdConnectBundle\Command\UserLoginCommand:
    public: true
    arguments:
      $cliLoginHelper: '@ItkDev\OpenIdConnectBundle\Util\CliLoginHelper'
      $cliLoginRoute: ~

  ItkDev\OpenIdConnectBundle\Security\CliLoginTokenAuthenticator:
    public: true
    arguments:
      $cliLoginHelper: '@ItkDev\OpenIdConnectBundle\Util\CliLoginHelper'
      $cliLoginRoute: ~
