name: Composer

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  composer-validate:
    name: Validate composer (${{ matrix.prefer }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        prefer: [prefer-lowest, prefer-stable]
    steps:
      - uses: actions/checkout@v5

      - run: |
          docker compose run --rm phpfpm composer validate --strict
          docker compose run --rm --user "$(id -u):$(id -g)" phpfpm composer update --${{ matrix.prefer }}

  composer-normalized:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v5

      - run: |
          docker compose run --rm --user "$(id -u):$(id -g)" phpfpm composer update
          docker compose run --rm --user "$(id -u):$(id -g)" phpfpm composer normalize --dry-run

  composer-audit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v5

      - run: |
          docker compose run --rm phpfpm composer audit
